---
title: HW 3
output: html_document
author: Артем Горохов
---

# Задание 12

```{r}
library(purrr)

weights = c(0.2, 0.3, 0.5)

w1 = 0.2
w2 = 0.3
w3 = 0.5

unif = function(n, a1,a2,a3,b1,b2,b3, i){
  if (i==1)
  return(runif(w1*n, a1, b1))
  else if (i==2)
    return(runif(w2*n, a2, b2))
  else if(i == 3)
      return((runif(w3*n, a3, b3)))
}


choose = function() {sample(1:3, 1, prob = weights)}

getSample = function(i,n,a1,a2,a3,b1,b2,b3){
  if (i == 1){
    result = list(list(1))
    for (k in 1:n) {
      result[[k]] = unif(n,a1,a2,a3,b1,b2,b3, as.numeric(unlist(choose())))
    }
    return(result)
  }
  
  else if(i == 2){
   return (c(runif(n*w1, a1, b1),
              runif(n*w2, a2, b2),
              runif(n*w3, a3, b3)))
  }
  else if(i == 3){
         s = (w1*(b1 - a1)*(b1 - a1)
            + w2*(b2 - a2)*(b2 - a2)
            + w3*(b3 - a3)*(b3 - a3)) /12
         n1 = n / 12 * w1*(b1 - a1)*(b1 - a1) / s
         n2 = n / 12 * w2*(b2 - a2)*(b2 - a2) / s
         n3 = n / 12 * w3*(b3 - a3)*(b3 - a3) / s
         
         s1 = runif(n1, a1, b1)
         s2 = runif(n2, a2, b2)
         s3 = runif(n3, a3, b3)
         return (c(s1,
                  s2,
                  s3))
  }
  else return(list(1,2,3))
}


calcMeansAndVars = function (n, a1,a2,a3,b1,b2,b3, s){
  
  data = list(list(list(1)))
  for (i in 1:3) {
        meansAndVars = list(list(1))
        for (j in 1:1000) {
          samp = unlist(getSample(as.numeric(unlist(i)), n, a1,a2,a3,b1,b2,b3))
          meansAndVars[[j]] = round(c(mean(samp), (n-1)/n * var(samp)),2)
        }

        means = unlist(map(meansAndVars, function(l) l[[1]]))
        vars = unlist(map(meansAndVars, function(l) l[[2]]))
        data[[i]] = list(means,vars)
  }
  
  names = c("Simple", "Prop", "Optimal")
  
  boxplot(data[[1]][[1]],data[[2]][[1]],data[[3]][[1]], main = sprintf("Mean %s N =%i", s, n), names = names)
  boxplot(data[[1]][[2]],data[[2]][[2]],data[[3]][[2]], main = sprintf("Var %s N =%i", s, n),  names = names)
  #hist(data[1][2],data[2][2],data[3][2])
}
```

```{r}

calcMeansAndVars(40, 0,0,0,100,100,100, "SameMeanAndVar")
calcMeansAndVars(500, 0,0,0,100,100,100, "SameMeanAndVar")
```

```{r}
calcMeansAndVars(40, 0, 100, 200, 100, 200, 300, "DiffMean_SameVar")
calcMeansAndVars(500, 0, 100, 200, 100, 200, 300, "DiffMean_SameVar")
```

```{r}
calcMeansAndVars(40, 0, 120, 15, 100, 185, 150, "DiffMeanAndVar")
calcMeansAndVars(500, 0, 120, 15, 100, 185, 150, "DiffMeanAndVar")
```

```{r}
```